version: "3.4"
services:
  reactivesearch-api:
    container_name: rs-api
    image: ghcr.io/appbaseio/reactivesearch-api:7.58.0
    restart: always
    depends_on:
      - reactivesearch-config-gui
    volumes:
      - reactivesearch-data:/reactivesearch-data
    ports:
      - 8000:8000
  nginx:
    container_name: appbase_nginx
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./reactivesearch-logo.svg:/etc/nginx/html/reactivesearch-logo.svg
      - ./nginx/certs:/etc/ssl/certs/
      - ./nginx/error.html:/etc/nginx/html/50x.html
      - www:/var/www/html
    ports:
      - 80:80
      - 443:443
    links:
      - reactivesearch-config-gui
  fluentbit:
    image: fluent/fluent-bit:1.5
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - reactivesearch-api
      - reactivesearch-config-gui
    restart: always
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parser.conf:/fluent-bit/etc/parser.conf
      - reactivesearch-data:/reactivesearch-data
  reactivesearch-config-gui:
    container_name: reactivesearch-config-gui
    image: appbaseio/reactivesearch-config-gui:0.3.0
    restart: always
    volumes:
      - reactivesearch-data:/reactivesearch-data
      - www:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  reactivesearch-data:
    external: false
    name: reactivesearch-data
  www:
    external: false
    name: www
