version: "3.4"
services:
  opensearch:
    image: 'opensearchproject/opensearch:3.2.0'
    container_name: opensearch
    environment:
      - 'DISABLE_SECURITY_PLUGIN=true'
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
      - '9600:9600'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './data:/usr/share/opensearch/data'
    networks:
      - reactivesearch_network

  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    container_name: zinc
    restart: always
    user: root
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
      - ZINC_DATA_PATH="/data"
    ports:
      - "4080:4080"
    volumes:
      - "zinc-data:/data"
    networks:
      - reactivesearch_network

  reactivesearch-api:
    container_name: rs-api
    image: appbaseio/reactivesearch-api:9.0.0.oss
    restart: always
    depends_on:
      - opensearch
      - zinc
    environment:
      - ES_CLUSTER_URL=http://opensearch:9200
      - ZINC_CLUSTER_URL=http://admin:Complexpass#123@zinc:4080
      - USERNAME=rs-admin-user
      - PASSWORD=rs-password
    volumes:
      - 'reactivesearch-data:/reactivesearch-data'
    ports:
      - '8000:8000'
    networks:
      - reactivesearch_network

  fluentbit:
    image: fluent/fluent-bit:4.0.8
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - reactivesearch-api
    restart: always
    volumes:
      - "./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro"
      - "./parser.conf:/fluent-bit/etc/parsers.conf:ro"
      - "reactivesearch-data:/reactivesearch-data"
      - "fluent-bit-state:/fluent-bit/state"
    networks:
      - reactivesearch_network

volumes:
  reactivesearch-data:
    external: false
    name: reactivesearch-data
  zinc-data:
    external: false
    name: zinc-data
  fluent-bit-state:
    external: false
    name: fluent-bit-state

networks:
  reactivesearch_network:
    driver: bridge