version: "3.4"
services:
  reactivesearch-api:
    container_name: rs-api
    image: appbaseio/reactivesearch-api:8.24.2.oss
    restart: always
    depends_on:
      - zinc
    volumes:
      - reactivesearch-data:/reactivesearch-data
    environment:
      - 'ES_CLUSTER_URL=http://elasticsearch:9200'
      - ZINC_CLUSTER_URL=http://admin:Complexpass#123@zinc:4080
      - USERNAME=rs-admin-user
      - PASSWORD=rs-password
    ports:
      - 8000:8000
    networks:
      - reactivesearch_network

  nginx:
    container_name: reactivesearch_api_nginx
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./reactivesearch-logo.svg:/etc/nginx/html/reactivesearch-logo.svg
      - ./nginx/certs:/etc/ssl/certs/
      - ./nginx/error.html:/etc/nginx/html/50x.html
      - www:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - reactivesearch_network

  fluentbit:
    image: fluent/fluent-bit:1.9.10
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - reactivesearch-api
    restart: always
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parser.conf:/fluent-bit/etc/parser.conf
      - reactivesearch-data:/reactivesearch-data
    networks:
      - reactivesearch_network

  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    container_name: zinc
    restart: always
    user: root
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
      - ZINC_DATA_PATH="/data"
    ports:
      - "4080:4080"
    volumes:
      - "zinc-data:/data"
    networks:
      - reactivesearch_network

volumes:
  reactivesearch-data:
    external: false
    name: reactivesearch-data
  www:
    external: false
    name: www
  zinc-data:
    external: false
    name: zinc-data

networks:
  reactivesearch_network:
    driver: bridge