version: "3.4"
services:
  reactivesearch-api:
    container_name: rs-api
    image: ghcr.io/appbaseio/reactivesearch-api:8.6.0
    restart: always
    depends_on:
      - reactivesearch-config-gui
      - zinc
    volumes:
      - reactivesearch-data:/reactivesearch-data
    ports:
      - 8000:8000
  nginx:
    container_name: appbase_nginx
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./reactivesearch-logo.svg:/etc/nginx/html/reactivesearch-logo.svg
      - ./nginx/certs:/etc/ssl/certs/
      - ./nginx/error.html:/etc/nginx/html/50x.html
      - www:/var/www/html
    ports:
      - 80:80
      - 443:443
    links:
      - reactivesearch-config-gui
  fluentbit:
    image: fluent/fluent-bit:1.9.4
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - reactivesearch-api
      - reactivesearch-config-gui
    restart: always
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parser.conf:/fluent-bit/etc/parser.conf
      - reactivesearch-data:/reactivesearch-data
  reactivesearch-config-gui:
    container_name: reactivesearch-config-gui
    image: appbaseio/reactivesearch-config-gui:0.3.1
    restart: always
    volumes:
      - reactivesearch-data:/reactivesearch-data
      - www:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    container_name: zinc
    restart: always
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
      - ZINC_DATA_PATH="/data"
    ports:
      - "4080:4080"
    volumes:
      - "zinc-data:/data"
volumes:
  reactivesearch-data:
    external: false
    name: reactivesearch-data
  www:
    external: false
    name: www
  zinc-data:
    external: false
    name: zinc-data
