version: '3'
services:
  opensearch:
    image: 'opensearchproject/opensearch:2.8.0'
    container_name: opensearch
    environment:
      - plugins.security.disabled=true
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
      - '9600:9600'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './data:/usr/share/opensearch/data'
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    container_name: zinc
    restart: always
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
      - ZINC_DATA_PATH="/data"
    ports:
      - "4080:4080"
    volumes:
      - "zinc-data:/data"
  reactivesearch-api:
    container_name: rs-api
    image: 'ghcr.io/appbaseio/reactivesearch-api:8.9.3'
    restart: always
    depends_on:
      - opensearch
      - zinc
    environment:
      - 'ES_CLUSTER_URL=http://opensearch:9200'
      - USERNAME=rs-admin-user
      - PASSWORD=rs-password
    volumes:
      - 'reactivesearch-data:/reactivesearch-data'
    ports:
      - '8000:8000'
  fluentbit:
    image: 'fluent/fluent-bit:1.9.10'
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - reactivesearch-api
    restart: always
    volumes:
      - './fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf'
      - './parser.conf:/fluent-bit/etc/parser.conf'
      - 'reactivesearch-data:/reactivesearch-data'
volumes:
  reactivesearch-data:
    external: false
    name: reactivesearch-data
  zinc-data:
    external: false
