version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - network.publish_host=_local_
      - network.host=_local_,_site_
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elasticsearch
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    container_name: zinc
    restart: always
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
      - ZINC_DATA_PATH="/data"
    ports:
      - "4080:4080"
    networks:
      - zinc
    volumes:
      - "zinc-data:/data"
  reactivesearch-api:
    container_name: rs-api
    image: ghcr.io/appbaseio/reactivesearch-api:8.6.0
    restart: always
    depends_on:
      - elasticsearch
      - zinc
    environment:
      - USERNAME=foo
      - PASSWORD=bar
      - SET_SNIFFING=false
      - APPBASE_ID=${ENTER_YOUR_APPBASE_ID}
      - ES_CLUSTER_URL=http://elasticsearch:9200
    volumes:
      - "reactivesearch-data:/reactivesearch-data"
    ports:
      - 8000:8000
    networks:
      - elasticsearch
  fluentbit:
    image: fluent/fluent-bit:1.9.4
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - "reactivesearch-api"
    restart: always
    volumes:
      - "./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
      - "./parser.conf:/fluent-bit/etc/parser.conf"
      - "reactivesearch-data:/reactivesearch-data"
volumes:
  reactivesearch-data:
    external: false
  zinc-data:
    external: false
networks:
  elasticsearch:
    driver: bridge
  network:
    driver: bridge
